# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

http:
  server_port: 80

automation ui: !include automations.yaml
automation manual: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml
lutron: !include lutron.yaml

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/card-mod.js

rest: !include_dir_merge_list rest/
template: !include_dir_merge_list templates/
