# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  packages: !include_dir_named packages/
  allowlist_external_dirs:
    - /tmp

# Text to speech
tts:
  - platform: google_translate

http:
  server_port: 80

automation ui: !include automations.yaml
automation manual: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
    - /hacsfiles/Bubble-Card/bubble-pop-up-fix.js

template: !include_dir_merge_list templates/
sensor: !include_dir_merge_list sensors/
utility_meter: !include utility_meter.yaml
alert: !include alert.yaml
notify: !include notify.yaml
