# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

http:
  server_port: 80

automation ui: !include automations.yaml
automation manual: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
    - /hacsfiles/Bubble-Card/bubble-pop-up-fix.js

rest: !include_dir_merge_list rest/
template: !include_dir_merge_list templates/
sensor: !include_dir_merge_list sensors/
mqtt:
  sensor: !include_dir_merge_list mqtt/sensor/
utility_meter: !include utility_meter.yaml
alert: !include alert.yaml
notify: !include notify.yaml

lovelace_gen:

lovelace:
  mode: storage
  dashboards:
    home-yaml:
      mode: yaml
      filename: dashboards/home.yaml
      title: Home
      icon: mdi:home
      show_in_sidebar: true

synapse:
