#!/usr/bin/env fish
# mise description="trigger a yarn build, wait a bit for syncthing, and then restart the addon"
# mise depends=["build"]

echo "Waiting for Syncthing"
sleep 30
mise run reload_addon
