#!/usr/bin/env fish
#MISE description="trigger a yarn build, wait a bit for syncthing, and then restart the addon"
#MISE depends=["build"]

echo "Waiting for Syncthing"
sleep 30
mise run reload_addon nolog
echo "Waiting for addon to boot once"
sleep 30
mise run reload_addon
