#!/usr/bin/env fish
# mise description="restart the addon, tailing the logs"
ssh homeassistant -t ha addons restart 3f718f42_code_runner
if set -q argv[1] && test $argv[1] != "nolog"
  mise run logs
end
