cover:
  - name: "Front Door"
    unique_id: "front_door"
    device_class: "door"
    state_topic: "rtl_433/MichaelRosensFridge/devices/Interlogix-Security/contact/af42c7/switch5"
    state_closed: "CLOSED"
    state_open: "OPEN"
    payload_close:
    device: &device
      manufacturer: Interlogix Security
      name: Front Door Sensor
      serial_number: &serial abe9b6
      identifiers:
        - *serial
binary_sensor:
  - name: "Front Door Battery"
    unique_id: "front_door_battery"
    device_class: battery
    state_topic: "rtl_433/MichaelRosensFridge/devices/Interlogix-Security/contact/af42c7/battery_ok"
    payload_off: 1
    payload_on: 0
    device: *device
  - name: "Front Door Tamper State"
    unique_id: "front_door_tamper"
    device_class: tamper
    state_topic: "rtl_433/MichaelRosensFridge/devices/Interlogix-Security/contact/af42c7/switch3"
    payload_off: "CLOSED"
    payload_on: "OPEN"
    device: *device
