esphome:
  name: esphome-web-659621
  friendly_name: Cat Feeder

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret cat_feeder_api

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-659621"
    password: "7h9sQ2jh8CRd"

captive_portal:

output:
  - platform: gpio
    pin: D5
    id: motor_relay
    inverted: true

button:
  - platform: output
    name: "Feed Cat"
    id: feed_cat
    output: motor_relay
    duration: 1s

time:
  - platform: homeassistant
    id: ha_time
    on_time:
      - hours: 8,16
        minutes: 0
        seconds: 0
        then:
          - button.press: feed_cat
          - homeassistant.event:
              event: esphome.feed_cat_cron_event
