esphome:
  name: "mailbox-abe59c"
  friendly_name: Mailbox
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Going to keep Deep Sleep turned off for now, so I can evaluate battery
# consumption I'm running off a rather large 18650 battery, so I'm interested to
# see how battery hungry it will be
# deep_sleep:
#   run_duration: 30s
#   sleep_duration: 10min
#   esp32_ext1_wakeup:
#     pins:
#       - GPIO6
#       - GPIO7
#     mode: ANY_HIGH
#   wakeup_pin_mode: KEEP_AWAKE

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO6
      inverted: true
      mode:
        input: true
        pullup: true
    id: top_door
    name: "Top Door"
    device_class: opening
    on_press:
      then:
        - binary_sensor.template.publish:
            id: new_mail
            state: ON
    filters:
      - delayed_on: 10ms
    # internal: true
  - platform: gpio
    pin:
      number: GPIO7
      inverted: true
      mode:
        input: true
        pullup: true
    id: bottom_door
    name: "Bottom Door"
    device_class: opening
    on_press:
      then:
        - binary_sensor.template.publish:
            id: new_mail
            state: OFF
    filters:
      - delayed_on: 10ms
    # internal: true
  - platform: template
    id: new_mail
    name: "New Mail"
    icon: mdi:mailbox-up

sensor:
  - platform: adc
    id: battery_voltage
    name: "Battery Voltage"
    pin: GPIO2
    unit_of_measurement: "V"
    device_class: voltage
    update_interval: 10s
    attenuation: auto
    filters:
      - multiply: 2.1
  - platform: template
    id: battery_percentage
    name: "Battery Percentage"
    icon: mdi:battery
    device_class: battery
    update_interval: 60s
    lambda: |-
        auto bat = id(battery_voltage).state;
        if (bat < 3.0) {
                return 0.0;
        } else if (bat > 4.2) {
          return 100.0;
        } else {
          // Linear interpolation between 3.0V and 4.2V
          return (bat - 3.0) * (100.0 / (4.2 - 3.0));
        }

button:
  - platform: template
    id: reset_mail
    name: "Reset Mail"
    icon: mdi:mailbox-outline
    on_press:
      then:
        - binary_sensor.template.publish:
            id: new_mail
            state: OFF
