sensor:
  # Do an integration on the gpm flow sensor
  - platform: integration
    source: sensor.droplet_ef38_flow_rate
    name: Total Water Used
    unique_id: droplet_total_water_used
    round: 2
    unit_time: min
    method: trapezoidal

utility_meter:
  daily_water_usage:
    source: sensor.total_water_used
    cycle: daily
    unique_id: droplet_daily_water_usage_u_m
